language: ruby
rvm:
  - 2.0.0
before_install:
  - wget https://github.com/zaproxy/zaproxy/releases/download/2.7.0/ZAP_2.7.0_Linux.tar.gz 
  - tar -xvf download
  - git submodule update --init --recursive
before_script:
  - pushd vendor/railsgoat
  - bundle exec rake db:setup
  - bundle exec rails server -d
  - popd
script:
  - zapr --summary --debug --zap-path $TRAVIS_BUILD_DIR/ZAP_2.7.0/zap.sh http://localhost:3000/
